(() => {
const stub = () => ({ style: {}, classList: { toggle() {}, add() {}, remove() {} }, setProperty() {}, addEventListener() {} });
const $ = (s, r = document) => r.querySelector(s) || stub(), $$ = (s, r = document) => [...r.querySelectorAll(s)];
const toast = m => { $('#toastB').textContent = m; bootstrap.Toast.getOrCreateInstance($('#toast')).show(); };
const saved = () => { try { return JSON.parse(localStorage.lf_saved || '[]'); } catch (e) { return []; } };
const F = [
 ['Green Textile Manufacturing Complex','Green Textile Ltd','Dhaka','Bangladesh','Textile','Gold',86,1],
 ['Sustainable Apparel Factory','EcoWear Co.','Hanoi','Vietnam','Garments','Platinum',92,1],
 ['Eco Industrial Park','Verde Industrial','Pune','India','Manufacturing','Silver',78,0],
 ['Green Home Textile Factory','HomeLoom','Istanbul','Turkey','Home Textile','Gold',84,1],
 ['Smart Manufacturing Facility','NovaTech','Chennai','India','Electronics','Certified',72,0],
 ['Sustainable Production Center','Terra Works','Gazipur','Bangladesh','Textile','Platinum',90,1],
 ['Solar Garment Hub','SunStitch','Ho Chi Minh City','Vietnam','Garments','Gold',83,0],
 ['Blue Water Dye House','AquaColor','Bursa','Turkey','Textile','Silver',76,1],
 ['Circular Electronics Plant','LoopCircuits','Bengaluru','India','Electronics','Gold',85,1],
 ['Evergreen Towel Mills','SoftLeaf','Narayanganj','Bangladesh','Home Textile','Certified',70,0],
 ['Net-Zero Assembly Works','ZeroLine','Danang','Vietnam','Manufacturing','Platinum',94,1],
 ['Greenfield Packaging','PackWell','Izmir','Turkey','Other','Silver',74,0]];
const CATS = [['Location & Transportation',16,11],['Sustainable Sites',10,7],['Water Efficiency',11,8],['Energy & Atmosphere',33,25],['Materials & Resources',13,7],['Indoor Environmental Quality',16,6],['Innovation',6,3],['Regional Priority',4,1]];
const SPOTS = [['Solar Plant',18,30,'Rooftop array supplying a large share of daily load.','72% renewable energy usage.','EA Credit: Renewable Energy Production'],
 ['ETP',72,62,'Effluent treatment plant returning treated water to process.','64% water reuse.','WE Credit: Process Water Use Reduction'],
 ['Production Floor',45,68,'Daylit knitting and sewing floor with efficient HVAC.','Daylight reaches most regularly occupied space.','EQ Credit: Daylight'],
 ['Water Treatment',85,48,'Rainwater harvesting and filtration tanks.','Cuts municipal water draw.','WE Credit: Outdoor Water Use Reduction'],
 ['Green Roof',32,45,'Vegetated roof lowering heat gain.','Reduces cooling load and runoff.','SS Credit: Heat Island Reduction'],
 ['Waste Management',60,82,'Segregation yard for textile offcuts and packaging.','91% waste recycling.','MR Credit: Construction and Demolition Waste Management']];
const GAL = ['Factory','Production','Sustainability','Solar','Water','Workers','Architecture'];
const KPI = [['Energy',72,'Renewable Energy Usage','bi-lightning-charge'],['Water',64,'Water Reuse','bi-droplet'],['Waste',91,'Waste Recycling','bi-recycle'],['Carbon',38,'Carbon Reduction','bi-cloud-minus']];
const FACTS = [['Factory Type','Textile Manufacturing'],['Industry','Textile & Garments'],['Location','Dhaka, Bangladesh'],['Established','2014'],['Employees','2,500+'],['Production Capacity','50,000 Units / Month']];
const LEED = [['Rating System','LEED BD+C'],['Version','v4'],['Project Type','Manufacturing Facility'],['Status','Certified'],['Level','Gold'],['Total Points','68'],['Project ID','LEED-XXXXXX']];
const card = ([k, v]) => `<div class="col-6 col-lg-4"><div class="card-x"><span>${k}</span><b>${v}</b></div></div>`;
$('#facts').innerHTML = FACTS.map(card).join('');
$('#leedInfo').innerHTML = LEED.map(card).join('');
$('#kpis').innerHTML = KPI.map(([n, v, l, i]) => `<div class="col-6 col-lg-3"><div class="card-x"><i class="bi ${i} fs-3 text-success"></i><span>${n}</span><b class="big">${v}%</b><span class="mb-2">${l}</span><div class="bar"><i data-w="${v}"></i></div></div></div>`).join('');
$('#score').innerHTML = CATS.map(([n, a, g], i) => { const p = Math.round(g / a * 100); return `<div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button ${i ? 'collapsed' : ''}" data-bs-toggle="collapse" data-bs-target="#c${i}">${n}<span class="ms-auto me-3 fw-bold">${g} / ${a}</span></button></h3><div id="c${i}" class="accordion-collapse collapse ${i ? '' : 'show'}" data-bs-parent="#score"><div class="accordion-body"><div class="d-flex justify-content-between small mb-1"><span>Available Points: ${a} · Achieved Points: ${g}</span><b>${p}%</b></div><div class="bar"><i data-w="${p}"></i></div></div></div></div>`; }).join('');
$('#gallery').innerHTML = GAL.map((g, i) => `<div class="col-6 col-md-4 col-lg-3"><button class="gal ph ph-${4 + i % 4}" data-i="${i}">${g}</button></div>`).join('');
$('#pano').innerHTML = SPOTS.map((s, i) => `<button class="hs" style="left:${s[1]}%;top:${s[2]}%" data-n="${s[0]}" data-i="${i}" aria-label="${s[0]}">${i + 1}</button>`).join('');

const io = new IntersectionObserver(es => es.forEach(e => {
  if (!e.isIntersecting) return; const t = e.target; io.unobserve(t);
  if (t.dataset.count) { const end = +t.dataset.count, s = performance.now(); (function f(n) { const k = Math.min((n - s) / 1400, 1); t.textContent = Math.round(end * k); if (k < 1) requestAnimationFrame(f); })(s); }
  if (t.dataset.w) t.style.width = t.dataset.w + '%';
  if (t.id === 'ring') t.style.setProperty('--p', t.dataset.p || 61.8);
  if (t.classList.contains('reveal') || t.classList.contains('rv')) t.classList.add('in');
}), { threshold: .3 });
$$('.sec .container > h2').forEach(h => h.classList.add('reveal'));
$$('[data-count],[data-w],#ring,.reveal').forEach(el => io.observe(el));
$$('[data-bs-toggle="tab"],.accordion-button').forEach(b => b.addEventListener('click', () => setTimeout(() => $$('[data-w]').forEach(e => { e.style.width = '0'; requestAnimationFrame(() => e.style.width = e.dataset.w + '%'); }), 80)));

const nav = $('#nav'), topBtn = $('#top');
const onScroll = () => { nav.classList.toggle('solid', scrollY > 60 || !!document.body.dataset.solid); topBtn.classList.toggle('show', scrollY > 500); };
addEventListener('scroll', onScroll, { passive: true }); onScroll();
topBtn.onclick = () => scrollTo({ top: 0, behavior: 'smooth' });
$$('.navbar-nav a').forEach(a => a.addEventListener('click', () => bootstrap.Collapse.getInstance($('#menu'))?.hide()));

const st = { q: '', t: '', c: '', l: '', s: 0, tour: false, p: 1 }, PER = 6;
const draw = () => {
  const list = F.filter(f => (!st.q || (f[0] + f[1] + f[2] + f[3]).toLowerCase().includes(st.q.toLowerCase())) && (!st.t || f[4] === st.t) && (!st.c || f[3] === st.c) && (!st.l || f[5] === st.l) && f[6] >= st.s && (!st.tour || f[7]));
  const pages = Math.max(1, Math.ceil(list.length / PER)); st.p = Math.min(st.p, pages);
  $('#fGrid').innerHTML = list.slice((st.p - 1) * PER, st.p * PER).map((f, i) => `<div class="col-md-6 col-lg-4"><article class="fcard"><button class="heart" data-id="${F.indexOf(f)}" aria-label="Save factory"><i class="bi ${saved().includes(F.indexOf(f)) ? 'bi-heart-fill' : 'bi-heart'}"></i></button><div class="ph ph-${4 + i % 4}" role="img" aria-label="${f[0]} exterior"></div><div class="body"><div class="d-flex gap-2 mb-2"><span class="lvl lvl-${f[5]}">LEED ${f[5]}</span>${f[7] ? '<span class="t360"><i class="bi bi-badge-3d"></i> 360° Tour Available</span>' : ''}</div><h3>${f[0]}</h3><p class="meta mb-1">${f[1]} · ${f[4]}</p><p class="meta"><i class="bi bi-geo-alt"></i> ${f[2]}, ${f[3]}</p><div class="small fw-bold mb-1">Sustainability ${f[6]}%</div><div class="bar mb-3"><i style="width:${f[6]}%"></i></div><a href="factory-details.html?id=${F.indexOf(f)}" class="btn btn-green btn-sm w-100">View Factory</a></div></article></div>`).join('');
  $('#fEmpty').classList.toggle('d-none', list.length > 0);
  $('#fPages').innerHTML = pages < 2 ? '' : Array.from({ length: pages }, (_, i) => `<li class="page-item ${i + 1 === st.p ? 'active' : ''}"><button class="page-link" data-p="${i + 1}">${i + 1}</button></li>`).join('');
};
const sync = () => { st.p = 1; draw(); };
$('#fSearch').oninput = e => { st.q = e.target.value; sync(); };
$('#fCountry').onchange = e => { st.c = e.target.value; sync(); };
$('#fLevel').onchange = e => { st.l = e.target.value; sync(); };
$('#fScore').onchange = e => { st.s = +e.target.value; sync(); };
$('#f360').onchange = e => { st.tour = e.target.checked; sync(); };
$('#fChips').onclick = e => { const b = e.target.closest('.chip'); if (!b) return; $$('.chip').forEach(c => c.classList.remove('active')); b.classList.add('active'); st.t = b.dataset.t; sync(); };
$('#fPages').onclick = e => { const b = e.target.closest('[data-p]'); if (b) { st.p = +b.dataset.p; draw(); } };
$('#heroSearch').onsubmit = e => { e.preventDefault(); st.q = $('#heroQ').value; st.c = $('#hCountry').value; st.t = $('#hInd').value; st.l = $('#hLevel').value; $('#fSearch').value = st.q; $('#fCountry').value = st.c; $('#fLevel').value = st.l; $$('.chip').forEach(c => c.classList.toggle('active', c.dataset.t === st.t)); sync(); $('#factories').scrollIntoView({ behavior: 'smooth' }); };
draw();

let zoom = 1, scene = 0;
const names = ['Main Floor', 'Rooftop', 'Yard'], pano = $('#pano');
const setScene = () => { $('#sceneName').textContent = 'Scene: ' + names[scene]; pano.style.filter = `hue-rotate(${scene * 25}deg)`; };
const setZoom = z => { zoom = Math.min(2, Math.max(1, z)); pano.style.transform = `scale(${zoom})`; };
$('#zin').onclick = () => setZoom(zoom + .25); $('#zout').onclick = () => setZoom(zoom - .25);
$('#prev').onclick = () => { scene = (scene + 2) % 3; setScene(); }; $('#next').onclick = () => { scene = (scene + 1) % 3; setScene(); };
$('#fs').onclick = () => document.fullscreenElement ? document.exitFullscreen() : $('#viewer').requestFullscreen?.();
$('#info').onclick = () => toast('Select a numbered hotspot to see sustainability evidence.');
setScene();
pano.onclick = e => { const b = e.target.closest('.hs'); if (!b) return; const s = SPOTS[b.dataset.i]; $('#hsT').textContent = s[0]; $('#hsD').textContent = s[3]; $('#hsS').textContent = s[4]; $('#hsC').textContent = s[5]; bootstrap.Modal.getOrCreateInstance($('#hsModal')).show(); };
$('#hsE').onclick = () => toast('Evidence document opened (demo).');

let gi = 0; const lb = () => { $('#lbImg').className = `ph lb ph-${4 + gi % 4}`; $('#lbT').textContent = GAL[gi]; };
$('#gallery').onclick = e => { const b = e.target.closest('.gal'); if (!b) return; gi = +b.dataset.i; lb(); bootstrap.Modal.getOrCreateInstance($('#lbModal')).show(); };
$('#lbP').onclick = () => { gi = (gi + GAL.length - 1) % GAL.length; lb(); }; $('#lbN').onclick = () => { gi = (gi + 1) % GAL.length; lb(); };

const form = (el, ok) => el.addEventListener('submit', e => { e.preventDefault(); el.classList.add('was-validated'); if (el.checkValidity()) { ok(); el.reset(); el.classList.remove('was-validated'); } });
form($('#contactForm'), () => toast('Thank you! Your message has been submitted.'));
form($('#loginForm'), () => { bootstrap.Modal.getInstance($('#authModal')).hide(); toast('Demo login successful.'); });
form($('#news'), () => toast('Subscribed. Thank you!'));

const PTS = { Certified: 45, Silver: 55, Gold: 66, Platinum: 82 }, ST = ['Certified', 'Under Review', 'Registered', 'Certified'];
const PR = F.map((f, i) => ({ id: i, n: 'LEED BD+C: ' + f[0], f: f[0], loc: f[2] + ', ' + f[3], l: f[5], s: PTS[f[5]] + i % 4, st: ST[i % 4], t: f[7] }));
const ARTS = [['LEED','Sep 28, 2026','What LEED v4 asks of a factory','The credit categories that matter most for manufacturing sites.'],['Sustainability','Sep 21, 2026','Reading a factory sustainability score','What the energy, water and waste figures include and leave out.'],['Green Building','Sep 14, 2026','Daylight on the production floor','How skylights and layout cut lighting load in garment plants.'],['Manufacturing','Sep 9, 2026','Heat recovery in dye houses','Reusing process heat to lower boiler fuel use.'],['Textile','Aug 30, 2026','Closed-loop water in textile mills','Treatment steps that let mills reuse most process water.'],['Case Studies','Aug 22, 2026','From Silver to Gold in two years','Upgrades one plant made to add 12 LEED points.'],['Reports','Aug 15, 2026','Green factory report 2026','Benchmarks from 250+ factories across 35 countries.'],['News','Aug 2, 2026','Three new Platinum factories listed','Facilities in Vietnam and Bangladesh join the platform.']];
const chips = (id, cb) => { const el = $(id); el.addEventListener('click', e => { const b = e.target.closest('.chip'); if (!b) return; $$('.chip', el).forEach(c => c.classList.remove('active')); b.classList.add('active'); cb(b.dataset.t); }); };
const lv = l => `<span class="lvl lvl-${l}">LEED ${l}</span>`;
const pj = (t = '') => { $('#pGrid').innerHTML = PR.filter(p => !t || p.st === t).map((p, i) => `<div class="col-md-6 col-lg-4"><article class="fcard"><div class="ph ph-${4 + i % 4}" role="img" aria-label="${p.f}"></div><div class="body"><div class="d-flex gap-2 mb-2">${lv(p.l)}<span class="badge text-bg-light border">${p.st}</span>${p.t ? '<span class="t360">360°</span>' : ''}</div><h3>${p.n}</h3><p class="meta mb-1">${p.f}</p><p class="meta"><i class="bi bi-geo-alt"></i> ${p.loc} · Score ${p.s}/110</p><div class="d-flex gap-2"><a class="btn btn-green btn-sm flex-fill" href="project-details.html?id=${p.id}">View Project</a><a class="btn btn-outline-success btn-sm flex-fill" href="scorecard.html">View Scorecard</a></div></div></article></div>`).join(''); };
if ($('#pGrid').innerHTML !== undefined && document.getElementById('pGrid')) { pj(); chips('#pChips', pj); }
if (document.getElementById('tGrid')) $('#tGrid').innerHTML = F.filter(f => f[7]).map((f, i) => `<div class="col-md-6 col-lg-4"><a class="tcard ph ph-${4 + i % 4}" href="factory-details.html?id=${F.indexOf(f)}#tour"><span class="t360"><i class="bi bi-badge-3d"></i> 360° TOUR</span><div><h3>${f[0]}</h3><p class="mb-2 small">${f[2]}, ${f[3]} · ${f[5]}</p><span class="btn btn-gold btn-sm">Start Virtual Tour</span></div></a></div>`).join('');
const art = (c = '') => { $('#aGrid').innerHTML = ARTS.filter(a => !c || a[0] === c).map((a, i) => `<div class="col-md-6 col-lg-3"><article class="acard"><div class="ph ph-${4 + i % 4}"></div><div class="body"><small>${a[0]} · ${a[1]}</small><h3 class="h6 mt-1">${a[2]}</h3><p class="small">${a[3]}</p><a href="#" class="fw-bold">Read More</a></div></article></div>`).join(''); };
if (document.getElementById('aGrid')) { art(); chips('#aChips', art); }
if (document.getElementById('pd')) { const p = PR[+new URLSearchParams(location.search).get('id')] || PR[0]; $('#pd').innerHTML = `<div class="row g-4"><div class="col-lg-7"><div class="cover ph ph-2"><div><h2 class="text-white">${p.n}</h2><p class="mb-0">${p.loc}</p></div></div></div><div class="col-lg-5"><div class="row g-3">${[['Level', p.l], ['Score', p.s + ' / 110'], ['Status', p.st], ['360° Tour', p.t ? 'Available' : 'Not yet']].map(card).join('')}</div><div class="d-flex gap-2 mt-3"><a class="btn btn-green" href="scorecard.html">View Scorecard</a><a class="btn btn-outline-success" href="factory-details.html?id=${p.id}">View Factory</a></div></div></div>`; }
document.addEventListener('click', e => { const h = e.target.closest('.heart'); if (!h) return; const id = +h.dataset.id, a = saved(), on = a.includes(id); const n = on ? a.filter(x => x !== id) : [...a, id]; try { localStorage.lf_saved = JSON.stringify(n); } catch (x) {} h.firstElementChild.className = 'bi ' + (on ? 'bi-heart' : 'bi-heart-fill'); toast(on ? 'Removed from saved factories.' : 'Saved to your dashboard.'); });
const th = () => { document.documentElement.dataset.theme = localStorage.lf_theme || 'light'; }; th();
$('#theme').onclick = () => { localStorage.lf_theme = localStorage.lf_theme === 'dark' ? 'light' : 'dark'; th(); };
document.addEventListener('keydown', e => { if (e.key === '/' && !/INPUT|TEXTAREA/.test(document.activeElement.tagName) && document.getElementById('fSearch')) { e.preventDefault(); $('#fSearch').focus(); } });
form($('#loginPage'), () => { toast('Demo login successful. Opening dashboard…'); setTimeout(() => location.href = 'dashboard.html', 900); });
$('#rp').oninput = e => { const v = e.target.value; const sc = (v.length > 7) + /[A-Z]/.test(v) + /\d/.test(v) + /\W/.test(v); $('#pw').style.width = sc * 25 + '%'; };
$('#regForm').addEventListener('submit', e => { e.preventDefault(); const v = id => $('#' + id).value.trim(), er = []; if (!v('rn')) er.push('Enter your full name.'); if (!/^\S+@\S+\.\S+$/.test(v('re'))) er.push('Enter a valid email address.'); if (v('rp').length < 8) er.push('Use a password of at least 8 characters.'); if (v('rp') !== v('rc')) er.push('Passwords do not match.'); $('#regAlert').innerHTML = er.length ? `<div class="alert alert-danger" role="alert">${er.join('<br>')}</div>` : ''; if (!er.length) { toast('Account created. Opening dashboard…'); setTimeout(() => location.href = 'dashboard.html', 900); } });
if (document.getElementById('p-ov')) {
  $$('.side [data-p]').forEach(b => b.onclick = () => { $$('.side [data-p]').forEach(x => x.classList.toggle('on', x === b)); $$('.dp').forEach(d => d.classList.toggle('d-none', d.id !== 'p-' + b.dataset.p)); window.dispatchEvent(new Event('resize')); });
  $('#set').onclick = () => toast('Settings are not part of this prototype.');
  $('#savedN').textContent = saved().length;
  $('#savedGrid').innerHTML = saved().length ? saved().map(i => `<div class="col-md-6 col-xl-4"><div class="card-x"><h3 class="h6">${F[i][0]}</h3><p class="meta">${F[i][2]}, ${F[i][3]}</p>${lv(F[i][5])}</div></div>`).join('') : '<p>No saved factories yet. Tap the heart on any factory card.</p>';
  $('#recent').innerHTML = F.slice(0, 5).map((f, i) => `<tr><td>${f[0]}</td><td>${i + 1} day${i ? 's' : ''} ago</td></tr>`).join('');
  if (window.Chart) { const M = ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'], C = [['bar', ['Certified', 'Silver', 'Gold', 'Platinum'], [18, 32, 41, 29]], ['line', M, [61, 64, 68, 71, 74, 78]], ['line', M, [58, 62, 65, 69, 70, 72]], ['bar', M, [48, 52, 55, 60, 62, 64]], ['doughnut', ['Recycled', 'Reused', 'Landfill'], [91, 6, 3]]], col = ['#0B5D3B', '#16865A', '#C9A227', '#12352A'];
    C.forEach((c, i) => new Chart(document.getElementById('ch' + i), { type: c[0], data: { labels: c[1], datasets: [{ data: c[2], borderColor: '#16865A', backgroundColor: c[0] === 'doughnut' ? col : c[0] === 'bar' ? '#16865A' : 'rgba(22,134,90,.15)', fill: c[0] === 'line', tension: .35 }] }, options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: c[0] === 'doughnut' } } } })); }
}

/* WORLD + HOME */
const SV = [['bi-patch-check','LEED Verification','Independent review of a factory\'s credits and evidence.'],['bi-badge-3d','360° Tour Production','Capture and publish tours linked to evidence.'],['bi-graph-up','Sustainability Benchmarking','Compare energy, water and waste against peers.'],['bi-clipboard-data','Scorecard Preparation','Gap analysis and credit documentation.'],['bi-lightbulb','Green Retrofit Advice','Plan upgrades that add LEED points.'],['bi-people','Buyer Matching','Connect verified factories with responsible buyers.']];
const PK = [['Starter',49,['1 factory profile','Public scorecard','Email support']],['Professional',149,['5 factory profiles','360° tour hosting','Evidence uploads','Priority support']],['Enterprise',399,['Unlimited profiles','Custom reports','Dedicated reviewer','API access']]];
const WH = [['bi-shield-check','Verified data','Buyers trust figures that link to evidence.'],['bi-globe2','Global buyer reach','Be found by buyers in 35+ countries.'],['bi-speedometer2','Faster audits','Share one profile instead of many files.'],['bi-piggy-bank','Lower running costs','Benchmarks show where energy and water are wasted.']];
const TS = [['Our buyers now ask for the scorecard link first. Audits that took weeks take days.','Farhana Akter','Sustainability Lead, Green Textile Ltd'],['The 360° tour let a buyer inspect our dye house without flying in.','Minh Tran','Operations Director, EcoWear Co.'],['Benchmarking showed our water use was above peers. We fixed it in a quarter.','Ahmet Kaya','Plant Manager, HomeLoom']];
const MG = [['Rahim Chowdhury','Chief Executive'],['Linh Tran','Head of LEED Verification'],['Aylin Demir','Director of Technology'],['Priya Nair','Head of Partnerships']];
const WM = [['Bangladesh',745,215,42,'Gold'],['Vietnam',800,240,31,'Platinum'],['India',700,225,38,'Gold'],['Turkey',570,155,24,'Silver'],['Germany',510,115,18,'Gold'],['USA',210,150,22,'Platinum'],['Brazil',340,340,12,'Silver'],['Ethiopia',590,260,8,'Certified'],['China',790,175,36,'Gold']];
const SI = [['Green Textile Complex',[72,64,91,38,80]],['Sustainable Apparel Factory',[81,74,95,52,88]],['Eco Industrial Park',[58,60,70,30,65]]], PILL = ['Energy','Water','Waste','Carbon','Social'];
const show = (id, f) => { if (document.getElementById(id)) f(); };
show('mks', () => {
  const info = i => { const w = WM[i]; $$('.mk').forEach((m, j) => m.classList.toggle('on', j === i)); $('#mapInfo').innerHTML = `<h3 class="h5">${w[0]}</h3><b class="big">${w[3]}</b><span>verified factories</span><p class="mt-3 mb-1">Top rating here: ${lv(w[4])}</p><p class="small mb-0">Select another marker to compare.</p>`; };
  $('#mks').innerHTML = WM.map((w, i) => `<circle class="mk" cx="${w[1]}" cy="${w[2]}" r="9" tabindex="0" role="button" aria-label="${w[0]}" data-i="${i}"><title>${w[0]}</title></circle>`).join('');
  $$('.mk').forEach(m => { const g = () => info(+m.dataset.i); m.addEventListener('mouseenter', g); m.addEventListener('focus', g); m.addEventListener('click', g); }); info(0);
});
show('hpGrid', () => $('#hpGrid').innerHTML = PR.slice(0, 3).map((p, i) => `<div class="col-md-6 col-lg-4"><article class="fcard"><div class="ph ph-${4 + i}" role="img" aria-label="${p.f}"></div><div class="body"><div class="d-flex gap-2 mb-2">${lv(p.l)}<span class="badge text-bg-light border">${p.st}</span></div><h3>${p.n}</h3><p class="meta"><i class="bi bi-geo-alt"></i> ${p.loc} · ${p.s}/110</p><a class="btn btn-green btn-sm w-100" href="project-details.html?id=${p.id}">View Project</a></div></article></div>`).join(''));
show('svGrid', () => $('#svGrid').innerHTML = SV.map(s => `<div class="col-md-6 col-lg-4"><div class="card-x"><div class="ic"><i class="bi ${s[0]}"></i></div><h3 class="h5">${s[1]}</h3><p class="mb-0">${s[2]}</p></div></div>`).join(''));
show('pkGrid', () => { const r = () => { const y = $('#bill').checked; $('#pkGrid').innerHTML = PK.map((p, i) => `<div class="col-md-4"><div class="pk ${i === 1 ? 'hot' : ''}"><h3 class="h5">${p[0]}</h3><div class="price">$${y ? p[1] * 10 : p[1]}<small class="fs-6 text-muted">/${y ? 'year' : 'month'}</small></div><ul class="list-unstyled my-3">${p[2].map(x => `<li><i class="bi bi-check2-circle text-success"></i> ${x}</li>`).join('')}</ul><a href="register.html" class="btn ${i === 1 ? 'btn-gold' : 'btn-outline-success'} w-100">Choose ${p[0]}</a></div></div>`).join(''); }; $('#bill').onchange = r; r(); });
show('clTrack', () => { const L = ['EcoWear', 'HomeLoom', 'NovaTech', 'Verde Industrial', 'AquaColor', 'SoftLeaf', 'ZeroLine', 'PackWell']; $('#clTrack').innerHTML = [...L, ...L].map(x => `<div class="logo">${x}</div>`).join(''); });
show('whyGrid', () => $('#whyGrid').innerHTML = WH.map(s => `<div class="col-md-6 col-lg-3"><div class="card-x"><div class="ic"><i class="bi ${s[0]}"></i></div><h3 class="h5">${s[1]}</h3><p class="mb-0">${s[2]}</p></div></div>`).join(''));
show('tInner', () => { $('#tInner').innerHTML = TS.map((t, i) => `<div class="carousel-item ${i ? '' : 'active'}"><blockquote>“${t[0]}”<footer class="mt-3 fs-6"><b>${t[1]}</b><br><span class="text-muted">${t[2]}</span></footer></blockquote></div>`).join(''); $('#tInd').innerHTML = TS.map((t, i) => `<button data-bs-target="#tCar" data-bs-slide-to="${i}" class="${i ? '' : 'active'}" aria-label="Testimonial ${i + 1}"></button>`).join(''); });
show('mgGrid', () => $('#mgGrid').innerHTML = MG.map(m => `<div class="col-6 col-lg-3"><div class="card-x text-center"><div class="av">${m[0].split(' ').map(x => x[0]).join('')}</div><h3 class="h6">${m[0]}</h3><p class="meta">${m[1]}</p><div class="soc"><i class="bi bi-linkedin me-2"></i><i class="bi bi-envelope"></i></div></div></div>`).join(''));
show('siChips', () => { const r = k => { const v = SI[k][1]; $('#siScore').textContent = Math.round(v.reduce((a, b) => a + b) / 5); $('#siBars').innerHTML = v.map((x, i) => `<div class="si-row"><div class="d-flex justify-content-between small fw-bold"><span>${PILL[i]}</span><span>${x}%</span></div><div class="bar"><i style="width:${x}%"></i></div></div>`).join(''); };
  $('#siChips').innerHTML = SI.map((s, i) => `<button class="chip ${i ? '' : 'active'}" data-t="${i}">${s[0]}</button>`).join(''); chips('#siChips', k => r(+k)); r(0); });
show('fiBody', () => { let k = 6, d = -1; const r = () => { $('#fiBody').innerHTML = [...F].sort((a, b) => (a[k] > b[k] ? 1 : -1) * d).map(f => `<tr><td><b>${f[0]}</b></td><td>${f[2]}, ${f[3]}</td><td>${f[4]}</td><td>${lv(f[5])}</td><td>${f[6]}%</td></tr>`).join(''); }; $$('#fiTbl th button').forEach(b => b.onclick = () => { const n = +b.dataset.k; d = n === k ? -d : 1; k = n; r(); }); r(); });
show('heroH', () => {
  const H = [['Discover the Future of Sustainable Factories', $('#heroP').textContent], ['Verify LEED Performance, Credit by Credit', 'Open any factory scorecard and see the points behind the level.'], ['Walk the Factory Floor in 360°', 'Inspect solar plants, treatment systems and production lines online.']], sl = $$('.slide'); let c = 0, t;
  $('#dots').innerHTML = H.map((h, i) => `<button class="${i ? '' : 'on'}" aria-label="Slide ${i + 1}"></button>`).join('');
  const go = n => { c = (n + 3) % 3; sl.forEach((s, i) => s.classList.toggle('on', i === c)); $$('#dots button').forEach((b, i) => b.classList.toggle('on', i === c)); $('#heroH').classList.add('fade-o'); $('#heroP').classList.add('fade-o'); setTimeout(() => { $('#heroH').textContent = H[c][0]; $('#heroP').textContent = H[c][1]; $('#heroH').classList.remove('fade-o'); $('#heroP').classList.remove('fade-o'); }, 350); };
  const auto = () => { clearInterval(t); t = setInterval(() => go(c + 1), 6000); }; auto();
  $('#slP').onclick = () => { go(c - 1); auto(); }; $('#slN').onclick = () => { go(c + 1); auto(); };
  $$('#dots button').forEach((b, i) => b.onclick = () => { go(i); auto(); });
});
const sp = document.createElement('div'); sp.id = 'sp'; document.body.prepend(sp);
addEventListener('scroll', () => { sp.style.width = scrollY / Math.max(1, document.documentElement.scrollHeight - innerHeight) * 100 + '%'; }, { passive: true });

/* V3 */
const TABS = { tour: 't6', scorecard: 't5', leed: 't4' };
const openTab = id => { const b = document.querySelector(`[data-bs-target="#${id}"]`); if (b) { bootstrap.Tab.getOrCreateInstance(b).show(); document.getElementById('profile')?.scrollIntoView({ behavior: 'smooth' }); } };
document.addEventListener('click', e => { const g = e.target.closest('[data-go]'); if (g) { e.preventDefault(); openTab(g.dataset.go); } const d = e.target.closest('.dl'); if (d) toast(d.textContent.trim() === 'Generate' ? 'Report generated (demo).' : 'Download started (demo).'); });
if (TABS[location.hash.slice(1)]) setTimeout(() => openTab(TABS[location.hash.slice(1)]), 300);
if (document.getElementById('pd')) { $('#pd').insertAdjacentHTML('beforeend', '<h3 class="h5 mt-5">Score by category</h3>' + CATS.map(c => `<div class="mb-3"><div class="d-flex justify-content-between small fw-bold"><span>${c[0]}</span><span>${c[2]} / ${c[1]}</span></div><div class="bar"><i data-w="${Math.round(c[2] / c[1] * 100)}"></i></div></div>`).join('')); $$('#pd [data-w]').forEach(el => io.observe(el)); }
document.addEventListener('click', e => { const a = e.target.closest('#aGrid a'); if (!a) return; e.preventDefault(); const t = a.closest('.body').querySelector('h3').textContent, r = ARTS.find(x => x[2] === t); if (!document.getElementById('artModal')) document.body.insertAdjacentHTML('beforeend', '<div class="modal fade" id="artModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="amT"></h5><button class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body" id="amB"></div></div></div></div>'); $('#amT').textContent = t; $('#amB').innerHTML = `<small class="text-muted">${r[0]} · ${r[1]}</small><p class="mt-2">${r[3]}</p><p class="mb-0">This is a prototype summary. The full article would load here from your content source.</p>`; bootstrap.Modal.getOrCreateInstance(document.getElementById('artModal')).show(); });

/* V4 */
show('mapSvg', () => {
  const W = window.WORLD, MC = { bd: [42, 'Gold'], vn: [31, 'Platinum'], in: [38, 'Gold'], tr: [24, 'Silver'], de: [18, 'Gold'], us: [22, 'Platinum'], br: [12, 'Silver'], et: [8, 'Certified'], cn: [36, 'Gold'] }, svg = $('#mapSvg'), tip = $('#mapTip'), box = svg.parentElement;
  if (!W) return; const [vx, vy, vw, vh] = W.vb.split(' ').map(Number); let sel = null;
  svg.setAttribute('viewBox', W.vb);
  svg.innerHTML = W.c.map(c => `<path class="cty ${MC[c[0]] ? 'has' : ''}" data-id="${c[0]}" d="${c[2]}"><title>${c[1]}</title></path>`).join('') + Object.keys(MC).map(k => `<circle class="mkr" cx="${W.mk[k][0]}" cy="${W.mk[k][1]}" r="5"/>`).join('');
  const nm = id => W.c.find(c => c[0] === id)[1];
  const view = (cx, cy, z) => { const w = vw / z, h = vh / z; const x = Math.max(0, Math.min(vw - w, cx - w / 2)), y = Math.max(0, Math.min(vh - h, cy - h / 2)); svg.setAttribute('viewBox', `${x} ${y} ${w} ${h}`); svg._v = [cx, cy, z]; }; view(vw / 2, vh / 2, 1);
  const pick = id => { sel = id; $$('.cty').forEach(p => p.classList.toggle('sel', p.dataset.id === id)); $$('#mapChips .chip').forEach(c => c.classList.toggle('active', c.dataset.t === id)); const m = MC[id]; $('#mapInfo').innerHTML = `<h3 class="h5">${nm(id)}</h3><b class="big">${m[0]}</b><span>verified factories</span><p class="mt-3 mb-1">Top rating: ${lv(m[1])}</p><a href="factories.html" class="btn btn-green btn-sm mt-2">Browse factories</a>`; view(W.mk[id][0], W.mk[id][1], 3); };
  $('#mapChips').innerHTML = Object.keys(MC).map(k => `<button class="chip" data-t="${k}">${nm(k)}</button>`).join('');
  $('#mapChips').onclick = e => { const b = e.target.closest('.chip'); if (b) pick(b.dataset.t); };
  svg.addEventListener('click', e => { const p = e.target.closest('.has'); if (p) pick(p.dataset.id); });
  svg.addEventListener('mousemove', e => { const p = e.target.closest('.cty'); if (!p) { tip.style.opacity = 0; return; } const r = box.getBoundingClientRect(); tip.textContent = nm(p.dataset.id) + (MC[p.dataset.id] ? ` · ${MC[p.dataset.id][0]} factories` : ''); tip.style.left = e.clientX - r.left + 12 + 'px'; tip.style.top = e.clientY - r.top + 12 + 'px'; tip.style.opacity = 1; });
  svg.addEventListener('mouseleave', () => tip.style.opacity = 0);
  const zz = d => { const v = svg._v; view(v[0], v[1], Math.max(1, Math.min(6, v[2] + d))); };
  document.getElementById('mzin').onclick = () => zz(1); document.getElementById('mzout').onclick = () => zz(-1); document.getElementById('mz0').onclick = () => { $$('.cty').forEach(p => p.classList.remove('sel')); $$('#mapChips .chip').forEach(c => c.classList.remove('active')); view(vw / 2, vh / 2, 1); };
  let drag = null; svg.addEventListener('pointerdown', e => { drag = [e.clientX, e.clientY, ...svg._v]; });
  addEventListener('pointerup', () => drag = null);
  svg.addEventListener('pointermove', e => { if (!drag || drag[4] <= 1) return; const k = vw / drag[4] / svg.clientWidth; view(drag[2] - (e.clientX - drag[0]) * k, drag[3] - (e.clientY - drag[1]) * k, drag[4]); });
  pick('bd');
});
show('tv', () => { const CH = [['Solar Plant', 0], ['Green Roof', 4.6], ['Production Floor', 9.2], ['Waste Management', 13.8], ['ETP', 18.4], ['Water Treatment', 23]], v = $('#tv'), n = 3;
  const T = 18 / 6; const CHP = CH.map((c, i) => [c[0], i * T]);
  $('#chap').innerHTML = CHP.map((c, i) => `<button data-t="${c[1]}"><span>${c[0]}</span><span>${Math.floor(c[1] / 60)}:${String(Math.floor(c[1] % 60)).padStart(2, '0')}</span></button>`).join('');
  $('#chap').onclick = e => { const b = e.target.closest('button'); if (b) { v.currentTime = +b.dataset.t; v.play(); } };
  v.addEventListener('timeupdate', () => { const i = Math.min(5, Math.floor(v.currentTime / T)); $$('#chap button').forEach((b, j) => b.classList.toggle('on', j === i)); }); });
show('hpGrid', () => { $('#hpGrid').insertAdjacentHTML('beforebegin', '<div class="d-flex flex-wrap gap-2 mb-4" id="hpChips">' + ['All', 'Platinum', 'Gold', 'Silver', 'Certified'].map((x, i) => `<button class="chip ${i ? '' : 'active'}" data-t="${i ? x : ''}">${x}</button>`).join('') + '</div>');
  const r = t => { $('#hpGrid').innerHTML = PR.filter(p => !t || p.l === t).slice(0, 6).map((p, i) => `<div class="col-md-6 col-lg-4"><article class="fcard"><div class="ph ph-${4 + i % 4}" role="img" aria-label="${p.f}"></div><div class="body"><div class="d-flex gap-2 mb-2">${lv(p.l)}<span class="badge text-bg-light border">${p.st}</span></div><h3>${p.n}</h3><p class="meta"><i class="bi bi-geo-alt"></i> ${p.loc} · ${p.s}/110</p><a class="btn btn-green btn-sm w-100" href="project-details.html?id=${p.id}">View Project</a></div></article></div>`).join(''); }; chips('#hpChips', r); r(''); });
show('fiQ', () => { const f = () => { const q = $('#fiQ').value.toLowerCase(); $$('#fiBody tr').forEach(tr => tr.hidden = !tr.textContent.toLowerCase().includes(q)); }; $('#fiQ').oninput = f; $$('#fiTbl th button').forEach(b => b.addEventListener('click', f)); });
$('#home').addEventListener('mousemove', e => { const x = (e.clientX / innerWidth - .5) * -14, y = (e.clientY / innerHeight - .5) * -10; $$('.slide').forEach(s => s.style.transform = `scale(1.06) translate(${x}px,${y}px)`); });
if (matchMedia('(hover:hover)').matches && !matchMedia('(prefers-reduced-motion:reduce)').matches) document.addEventListener('mousemove', e => { const c = e.target.closest && e.target.closest('.card-x,.pk,.acard,.fcard'); $$('.tilting').forEach(x => { if (x !== c) { x.style.transform = ''; x.classList.remove('tilting'); } }); if (!c || c.querySelector('canvas')) return; const r = c.getBoundingClientRect(), x = (e.clientX - r.left) / r.width - .5, y = (e.clientY - r.top) / r.height - .5; c.classList.add('tilting'); c.style.transform = `perspective(800px) rotateX(${-y * 5}deg) rotateY(${x * 6}deg) translateY(-4px)`; c.style.setProperty('--mx', (x + .5) * 100 + '%'); c.style.setProperty('--my', (y + .5) * 100 + '%'); });
show('viewer', () => { const v = $('#viewer'), TP = [40, 62, 58, 60, 38, 72]; let z = 1, x = 0, y = 0, cur = 0;
  $$('.hs', pano).forEach((h, i) => h.style.top = TP[i] + '%'); pano.style.backgroundSize = '100% 100%';
  const lay = () => { const vw = v.clientWidth, vh = v.clientHeight; if (!vw) return; pano.style.inset = 'auto'; pano.style.width = 300 * z + '%'; pano.style.height = 100 * z + '%'; x = Math.min(0, Math.max(vw - vw * 3 * z, x)); y = Math.min(0, Math.max(vh - vh * z, y)); pano.style.left = x + 'px'; pano.style.top = y + 'px'; pano.style.transform = 'none'; };
  const go = i => { cur = (i + SPOTS.length) % SPOTS.length; const vw = v.clientWidth; x = vw / 2 - SPOTS[cur][1] / 100 * vw * 3 * z; pano.style.transition = 'left .7s,top .7s'; lay(); $('#sceneName').textContent = SPOTS[cur][0]; setTimeout(() => pano.style.transition = '', 750); };
  $('#zin').onclick = () => { z = Math.min(2.5, z + .25); lay(); }; $('#zout').onclick = () => { z = Math.max(1, z - .25); lay(); }; $('#prev').onclick = () => go(cur - 1); $('#next').onclick = () => go(cur + 1);
  let d = null; pano.addEventListener('pointerdown', e => { d = [e.clientX, e.clientY, x, y]; }); addEventListener('pointerup', () => d = null); addEventListener('pointermove', e => { if (!d) return; x = d[2] + e.clientX - d[0]; y = d[3] + e.clientY - d[1]; lay(); });
  addEventListener('resize', lay); document.addEventListener('shown.bs.tab', () => go(cur)); go(0); });

/* V5 */
show('facts', () => { const cv = document.querySelector('#profile .cover'); if (!cv) return;
  const id = Math.max(0, Math.min(F.length - 1, +new URLSearchParams(location.search).get('id') || 0)), f = F[id], base = PTS[f[5]], r = base / 68;
  const cc = CATS.map(c => [c[0], c[1], Math.min(c[1], Math.round(c[2] * r))]), tot = cc.reduce((a, c) => a + c[2], 0);
  document.title = f[0] + ' | LEED Factories'; cv.querySelector('h2').textContent = f[0];
  cv.querySelector('p').innerHTML = `<i class="bi bi-geo-alt"></i> ${f[2]}, ${f[3]} &nbsp; ${lv(f[5])} &nbsp; Sustainability Score: ${f[6]}`;
  $('#facts').innerHTML = [['Factory Type', f[4] + ' Manufacturing'], ['Industry', f[4]], ['Location', f[2] + ', ' + f[3]], ['Established', 2008 + id % 12], ['Employees', (1200 + id * 210).toLocaleString() + '+'], ['Production Capacity', (30 + id * 4) + ',000 Units / Month']].map(card).join('');
  const e = f[6], V = [e - 14, e - 22, Math.min(98, e + 5), Math.round(e / 2.2)];
  $('#kpis').innerHTML = KPI.map(([n, , l, i], j) => `<div class="col-6 col-lg-3"><div class="card-x"><i class="bi ${i} fs-3 text-success"></i><span>${n}</span><b class="big">${V[j]}%</b><span class="mb-2">${l}</span><div class="bar"><i data-w="${V[j]}"></i></div></div></div>`).join('');
  $('#leedInfo').innerHTML = [['Rating System', 'LEED BD+C'], ['Version', 'v4'], ['Project Type', f[4] + ' Facility'], ['Status', 'Certified'], ['Level', f[5]], ['Total Points', tot], ['Project ID', 'LEED-' + (100000 + id * 137)]].map(card).join('');
  const rg = $('#ring'); rg.dataset.p = tot / 110 * 100; rg.querySelector('b').textContent = tot + ' / 110'; rg.querySelector('span').textContent = 'LEED ' + f[5];
  $('#score').innerHTML = cc.map(([n, a, g], i) => { const p = Math.round(g / a * 100); return `<div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button ${i ? 'collapsed' : ''}" data-bs-toggle="collapse" data-bs-target="#c${i}">${n}<span class="ms-auto me-3 fw-bold">${g} / ${a}</span></button></h3><div id="c${i}" class="accordion-collapse collapse ${i ? '' : 'show'}" data-bs-parent="#score"><div class="accordion-body"><div class="d-flex justify-content-between small mb-1"><span>Available Points: ${a} · Achieved Points: ${g}</span><b>${p}%</b></div><div class="bar"><i data-w="${p}"></i></div></div></div></div>`; }).join('');
  const bg = $$('#t5 .big'); if (bg[1]) { bg[1].textContent = tot; bg[2].textContent = (tot / 110 * 100).toFixed(1) + '%'; }
  $$('#kpis [data-w],#score [data-w]').forEach(el => io.observe(el)); });
document.addEventListener('click', e => { const c = e.target.closest('.fcard'); if (!c || e.target.closest('a,button')) return; const a = c.querySelector('a[href]'); if (a) location.href = a.href; });
show('mzp', () => { let t = 0; const K = ['bd', 'vn', 'in', 'tr', 'de', 'us', 'br', 'et', 'cn'], b = $('#mzp'); let i = 0; b.onclick = () => { if (t) { clearInterval(t); t = 0; b.innerHTML = '<i class="bi bi-play-fill"></i>'; } else { b.innerHTML = '<i class="bi bi-pause-fill"></i>'; t = setInterval(() => { i = (i + 1) % K.length; document.querySelector(`#mapChips [data-t="${K[i]}"]`)?.click(); }, 2500); } }; });
show('tqQ', () => { const D = [['Our buyers now ask for the scorecard link first. Audits that took weeks take days.', 'Farhana Akter', 'Sustainability Lead, Green Textile Ltd', 'Audit time −60%', '1573496359142-b8d87734a5a2'], ['The 360° tour let a buyer inspect our dye house without flying in.', 'Minh Tran', 'Operations Director, EcoWear Co.', '3 new buyers', '1560250097-0b93528c311a'], ['Benchmarking showed our water use was above peers. We fixed it in a quarter.', 'Ahmet Kaya', 'Plant Manager, HomeLoom', 'Water use −22%', '1519085360753-af0119f7cbe7'], ['One verified profile replaced six different supplier questionnaires.', 'Sara Lindqvist', 'Sourcing Manager, NordWear', 'Questionnaires −83%', '1580489944761-15a19d654956'], ['Gold to Platinum took two years. The scorecard showed exactly which credits to chase.', 'Linh Pham', 'Director, ZeroLine', '+14 LEED points', '1573497019940-1c28c88b4f3e'], ['Listing here gave us visibility with buyers in markets we had never reached.', 'Rafiq Hasan', 'CEO, SoftLeaf Mills', 'Export orders +31%', '1507003211169-0a1dd7228f2d']];
  const ini = n => n.split(' ').map(x => x[0]).join(''), av = d => `${ini(d[1])}<img src="https://images.unsplash.com/photo-${d[4]}?auto=format&fit=crop&w=160&h=160&q=70" alt="" onerror="this.remove()">`;
  $('#tqL').innerHTML = D.map((d, i) => `<button class="tqi" data-i="${i}"><span class="av3">${av(d)}</span><span><b>${d[1]}</b><small>${d[2].split(',')[1] || d[2]}</small></span></button>`).join('');
  let c = 0, t, play = true; const box = $('#tq');
  const set = i => { c = (i + D.length) % D.length; box.classList.add('sw'); setTimeout(() => { const d = D[c]; $('#tqS').textContent = '★★★★★'; $('#tqQ').textContent = '“' + d[0] + '”'; $('#tqN').textContent = d[1]; $('#tqR').textContent = d[2]; $('#tqM').textContent = d[3]; $('#tqA').innerHTML = av(d); box.classList.remove('sw'); const p = $('#tqP'); p.style.animation = 'none'; void p.offsetWidth; p.style.animation = ''; }, 220); $$('.tqi').forEach((b, j) => b.classList.toggle('on', j === c)); };
  const run = () => { clearTimeout(t); if (play) t = setTimeout(() => { set(c + 1); run(); }, 7000); };
  $('#tqL').onclick = e => { const b = e.target.closest('.tqi'); if (b) { set(+b.dataset.i); run(); } };
  $('#tqPrev').onclick = () => { set(c - 1); run(); }; $('#tqNext').onclick = () => { set(c + 1); run(); };
  $('#tqPlay').onclick = () => { play = !play; box.classList.toggle('paused', !play); $('#tqPlay').innerHTML = `<i class="bi bi-${play ? 'pause' : 'play'}-fill"></i>`; run(); };
  set(0); run(); });
show('hwS', () => { const S = [['bi-search', 'Discover', 'Search by country, industry, LEED level or score to find factories that fit.', 'factories.html', 'Explore factories'], ['bi-building', 'View Factory', 'Open a factory profile with its facts, capacity and certifications.', 'factory-details.html?id=0', 'Open a profile'], ['bi-leaf', 'Explore Sustainability', 'See renewable energy, water reuse, waste recycling and carbon cuts.', 'factory-details.html?id=0', 'See the KPIs'], ['bi-patch-check', 'Check LEED', 'Confirm the rating system, version, level and total points.', 'leed.html', 'See LEED levels'], ['bi-clipboard-data', 'View Scorecard', 'Open each credit category to see points earned against points available.', 'scorecard.html', 'Open scorecard'], ['bi-badge-3d', 'Open 360° Tour', 'Walk the site and select hotspots on solar, treatment and production areas.', 'tours.html', 'Start a tour'], ['bi-file-earmark-check', 'View Evidence', 'Every hotspot links to the document that backs the credit.', 'factory-details.html?id=0#tour', 'View evidence']];
  let c = 0, t, play = true;
  $('#hwS').innerHTML = S.map((s, i) => `<li><button class="hws" data-i="${i}"><span class="dot">${i + 1}</span><small>${s[1]}</small></button></li>`).join('');
  const set = i => { c = (i + S.length) % S.length; const s = S[c]; $$('.hws').forEach((b, j) => { b.classList.toggle('on', j === c); b.classList.toggle('done', j < c); }); $('#hwFill').style.width = c / (S.length - 1) * 100 + '%'; $('#hwP').innerHTML = `<div class="ic"><i class="bi ${s[0]}"></i></div><div><h3 class="h5">${c + 1}. ${s[1]}</h3><p class="mb-0">${s[2]}</p></div><a class="btn btn-green" href="${s[3]}">${s[4]}</a>`; };
  const run = () => { clearInterval(t); if (play) t = setInterval(() => set(c + 1), 4000); };
  $('#hwS').onclick = e => { const b = e.target.closest('.hws'); if (b) { set(+b.dataset.i); run(); } };
  $('#hwS').onmouseover = e => { const b = e.target.closest('.hws'); if (b && +b.dataset.i !== c) { set(+b.dataset.i); clearInterval(t); } };
  $('#journey').addEventListener('mouseleave', run);
  $('#hwPrev').onclick = () => { set(c - 1); run(); }; $('#hwNext').onclick = () => { set(c + 1); run(); };
  $('#hwPlay').onclick = () => { play = !play; $('#hwPlay').innerHTML = `<i class="bi bi-${play ? 'pause' : 'play'}-fill"></i>`; run(); };
  set(0); run(); });
show('svGrid', () => { const B = [['Document review', 'Gap analysis', 'Auditor sign-off'], ['Drone and 360° capture', 'Hotspot tagging', 'Evidence links'], ['Peer comparison', 'Monthly trend charts', 'Target setting'], ['Credit checklist', 'Document templates', 'Submission support'], ['Energy and water audit', 'Payback estimates', 'Upgrade roadmap'], ['Verified profile', 'Buyer enquiries', 'Introduction calls']];
  $('#svGrid').innerHTML = SV.map((s, i) => `<div class="col-md-6 col-lg-4"><div class="card-x sv"><div class="ic"><i class="bi ${s[0]}"></i></div><h3 class="h5">${s[1]}</h3><p class="mb-0">${s[2]}</p><ul class="sv-l">${B[i].map(x => `<li><i class="bi bi-check2 text-success"></i> ${x}</li>`).join('')}</ul><button class="more">What's included</button></div></div>`).join('');
  $('#svGrid').onclick = e => { const b = e.target.closest('.more'); if (b) b.closest('.sv').classList.toggle('open'); }; });
show('whyGrid', () => { const N = [[100, '%', 'of figures link to evidence'], [35, '+', 'countries of buyers'], [60, '%', 'shorter audit prep'], [22, '%', 'average water saving']];
  $('#whyGrid').innerHTML = WH.map((s, i) => `<div class="col-md-6 col-lg-3"><div class="card-x"><div class="ic"><i class="bi ${s[0]}"></i></div><b class="big"><span data-count="${N[i][0]}">0</span>${N[i][1]}</b><span>${N[i][2]}</span><h3 class="h6 mt-3">${s[1]}</h3><p class="mb-0 small">${s[2]}</p></div></div>`).join(''); $$('#whyGrid [data-count]').forEach(el => io.observe(el)); });
show('siRing', () => { const f = () => $('#siRing').style.setProperty('--p', +$('#siScore').textContent); chips('#siChips', () => setTimeout(f, 30)); setTimeout(f, 80); });
['#svGrid', '#whyGrid', '#mgGrid'].forEach(g => $$(g + ' > *').forEach((el, i) => { el.classList.add('rv'); el.style.setProperty('--d', i * .08 + 's'); io.observe(el); }));

/* V6 */
const dm = (t, h) => { let m = document.getElementById('dm'); if (!m) { document.body.insertAdjacentHTML('beforeend', '<div class="modal fade" id="dm" tabindex="-1"><div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="dmT"></h5><button class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body" id="dmB"></div></div></div></div>'); m = document.getElementById('dm'); } document.getElementById('dmT').textContent = t; document.getElementById('dmB').innerHTML = h; bootstrap.Modal.getOrCreateInstance(m).show(); };
const NEWS = [
 ['LEED', 'Sep 30, 2026', 'The LEED v4 credits that matter most for textile mills', 'Energy and water credits carry the most points for wet-processing sites.', 6, ['Textile mills spend most of their energy on heat and most of their water on dyeing and finishing. That is why Energy & Atmosphere and Water Efficiency decide the level for most plants.', 'Factories that start with metering and heat recovery usually reach Silver before touching the building. Rooftop solar and effluent reuse then add the points needed for Gold.'], 'Start with metering: you cannot score credits you cannot measure.'],
 ['Platform', 'Sep 24, 2026', '360° tours now link every hotspot to its evidence', 'Each hotspot opens the document that backs the credit.', 4, ['Buyers asked for proof, not only pictures. Every hotspot in a tour now shows the LEED credit it supports and a button to the evidence file.', 'Factories can add hotspots from their dashboard. Reviewers see which credits still lack documents.'], 'Hotspots turn a tour into an audit trail.'],
 ['Case Study', 'Sep 17, 2026', 'How one Dhaka complex earned LEED Gold', 'Solar, effluent reuse and daylighting added 68 points.', 7, ['The complex combined 2.4 MW of rooftop solar with an on-site effluent plant that returns treated water to process. Daylight now reaches most of the production floor.', 'The team documented each upgrade as it happened, which cut review time by weeks.'], 'Document upgrades as you build them, not afterwards.'],
 ['Industry', 'Sep 9, 2026', 'Heat recovery cuts boiler fuel in dye houses', 'Reusing hot effluent preheats fresh process water.', 5, ['Hot dye-bath effluent carries heat that is usually lost. Heat exchangers move it to incoming water and lower boiler load.', 'Payback is often under two years, and the savings show up directly in the energy score.'], 'Recover heat before you buy more fuel.'],
 ['Platform', 'Aug 28, 2026', 'The Sustainable Index adds a social pillar', 'Energy, water, waste, carbon and now worker wellbeing.', 3, ['The index now scores five pillars. The new social pillar covers safety record, working hours and worker feedback.', 'Scores are shown beside each factory so buyers can compare like with like.'], 'A good factory is measured on people as well as resources.'],
 ['Industry', 'Aug 15, 2026', 'Three new Platinum factories join the directory', 'New listings in Vietnam and Bangladesh reach 80+ points.', 4, ['Three facilities completed review this month and now hold LEED Platinum. Two are garment plants and one assembles electronics.', 'All three published full scorecards and 360° tours at listing.'], 'Platinum plants share their data openly.'],
 ['LEED', 'Aug 3, 2026', 'Daylight credits: what reviewers look for', 'Simulations and measured readings both count, if documented.', 5, ['The daylight credit rewards floors where most regularly occupied space gets enough natural light. Reviewers accept simulation results or on-site readings.', 'Clear skylight maps and dated light-meter logs make the review quicker.'], 'Keep dated measurements with floor plans.'],
 ['Case Study', 'Jul 20, 2026', 'A Vietnamese garment plant halves its water draw', 'Rainwater harvesting and a closed rinse loop did most of the work.', 6, ['The plant collects roof rainwater for washing and reuses rinse water in a closed loop.', 'Municipal draw fell by half within a year, and the plant gained Water Efficiency points.'], 'Reuse rinse water before adding treatment capacity.']];
const nth = i => 'ph-' + (4 + i % 4);
show('nGrid', () => { const cats = ['All', 'Platform', 'LEED', 'Industry', 'Case Study']; $('#nChips').innerHTML = cats.map((c, i) => `<button class="chip ${i ? '' : 'active'}" data-t="${i ? c : ''}">${c}</button>`).join('');
  const r = t => { const L = NEWS.map((n, i) => [n, i]).filter(x => !t || x[0][0] === t), [f, ...o] = L; $('#nGrid').innerHTML = `<div class="col-lg-7"><a class="nf ph ${nth(f[1])}" href="news-details.html?id=${f[1]}"><div><span class="lvl lvl-Gold">${f[0][0]}</span><h3 class="mt-2">${f[0][2]}</h3><p>${f[0][3]}</p><small>${f[0][1]} · ${f[0][4]} min read</small></div></a></div><div class="col-lg-5 d-flex flex-column gap-3">${o.slice(0, 3).map(x => `<a class="nl card-x" href="news-details.html?id=${x[1]}"><span class="nth ph ${nth(x[1])}"></span><span><small>${x[0][0]} · ${x[0][1]}</small><b>${x[0][2]}</b></span></a>`).join('')}</div>`; }; chips('#nChips', r); r(''); });
show('ndB', () => { const id = Math.min(NEWS.length - 1, Math.max(0, +new URLSearchParams(location.search).get('id') || 0)), n = NEWS[id]; document.title = n[2] + ' | LEED Factories';
  $('#ndC').textContent = n[0]; $('#ndT').textContent = n[2]; $('#ndM').textContent = `${n[1]} · ${n[4]} min read`; $('#ndI').className = `ph ${nth(id)} ndcover`;
  $('#ndB').innerHTML = `<p class="lead">${n[3]}</p>` + n[5].map(p => `<p>${p}</p>`).join('') + `<div class="take"><b>Key takeaway</b><p class="mb-0">${n[6]}</p></div>`;
  const N = NEWS.length, pv = (id + N - 1) % N, nx = (id + 1) % N; $('#ndN').innerHTML = `<a class="btn btn-outline-success" href="news-details.html?id=${pv}"><i class="bi bi-arrow-left"></i> Previous</a><a class="btn btn-green" href="news-details.html?id=${nx}">Next story <i class="bi bi-arrow-right"></i></a>`;
  $('#ndR').innerHTML = NEWS.map((x, i) => [x, i]).filter(x => x[1] !== id).slice(0, 3).map(x => `<a class="nl card-x" href="news-details.html?id=${x[1]}"><span class="nth ph ${nth(x[1])}"></span><span><small>${x[0][0]} · ${x[0][1]}</small><b>${x[0][2]}</b></span></a>`).join('');
  $('#ndCopy').onclick = () => { try { navigator.clipboard.writeText(location.href); } catch (e) {} toast('Link copied.'); }; form($('#news2'), () => toast('Subscribed. Thank you!')); });
show('whyTabs', () => { const W = [['bi-building', 'Factories', 'Turn your sustainability work into orders', ['Publish one verified profile instead of answering every buyer questionnaire.', 'Show your LEED scorecard, KPIs and 360° tour to buyers in 35+ countries.', 'Benchmark energy, water and waste against peers and see where to improve.', 'Track which credits are missing before the next audit.'], [[60, '%', 'shorter audit prep'], [31, '%', 'average export order growth']]], ['bi-bag-check', 'Buyers', 'Check claims before you commit', ['Compare factories on the same five-pillar index.', 'Open any scorecard and see points earned per credit.', 'Walk the site in 360° and view the evidence behind each hotspot.', 'Save factories and get alerts when their ratings change.'], [[83, '%', 'fewer supplier questionnaires'], [250, '+', 'factories to compare']]], ['bi-clipboard-check', 'Auditors', 'Review evidence in one place', ['Receive documents organised by LEED credit.', 'Leave comments on each credit and request missing files.', 'Sign off credits and publish the result to the profile.', 'Keep a full history of every rating change.'], [[40, '%', 'less time chasing files'], [120, '+', 'projects supported']]]];
  let c = 0; $('#whyTabs').innerHTML = W.map((w, i) => `<button class="audtab ${i ? '' : 'on'}" data-i="${i}"><i class="bi ${w[0]}"></i>${w[1]}</button>`).join('');
  const r = i => { const w = W[i]; $('#whyPanel').innerHTML = `<div class="row g-4"><div class="col-lg-7"><h3>${w[2]}</h3><ul class="wp-list">${w[3].map(x => `<li><i class="bi bi-check-circle-fill"></i><span>${x}</span></li>`).join('')}</ul><a href="register.html" class="btn btn-green">Create a ${w[1].slice(0, -1).toLowerCase()} account</a></div><div class="col-lg-5"><div class="row g-3 h-100">${w[4].map(s => `<div class="col-6 col-lg-12"><div class="wp-stat"><b class="big"><span data-count="${s[0]}">0</span>${s[1]}</b><div>${s[2]}</div></div></div>`).join('')}</div></div></div>`; $$('#whyPanel [data-count]').forEach(el => io.observe(el)); };
  $('#whyTabs').onclick = e => { const b = e.target.closest('.audtab'); if (!b) return; $$('.audtab').forEach(x => x.classList.toggle('on', x === b)); r(+b.dataset.i); }; r(0); });
show('svGrid', () => { const S = [['bi-patch-check', 'LEED Verification', 'Independent review of credits and evidence.', 'Verify', '4–8 weeks', '$1,800', 'We check each claimed credit against documents and site evidence, then publish the verified result to your profile.', ['Credit-by-credit review report', 'Verified badge on your profile', 'Gap list for missing evidence']], ['bi-badge-3d', '360° Tour Production', 'Capture and publish tours linked to evidence.', 'Digital', '2–3 weeks', '$1,200', 'Our crew captures your site, tags hotspots to LEED credits and hosts the tour on your profile.', ['360° capture of key areas', 'Tagged hotspots with evidence links', 'Hosted, shareable tour']], ['bi-graph-up', 'Sustainability Benchmarking', 'Compare energy, water and waste with peers.', 'Advisory', '1–2 weeks', '$600', 'We compare your metrics with similar factories and show where the biggest gaps are.', ['Peer comparison report', 'Monthly trend charts', 'Three prioritised targets']], ['bi-clipboard-data', 'Scorecard Preparation', 'Gap analysis and credit documentation.', 'Verify', '3–6 weeks', '$1,500', 'We map your site to LEED credits, find the cheapest points and prepare the submission files.', ['Credit checklist', 'Document templates', 'Submission support']], ['bi-lightbulb', 'Green Retrofit Advice', 'Plan upgrades that add LEED points.', 'Advisory', '3–5 weeks', '$2,400', 'Energy and water audits lead to a costed upgrade plan ranked by payback and points gained.', ['Energy and water audit', 'Payback estimates', 'Upgrade roadmap']], ['bi-people', 'Buyer Matching', 'Connect verified factories with responsible buyers.', 'Digital', 'Ongoing', '$300/mo', 'Your verified profile is shown to buyers searching for your industry and rating.', ['Priority placement', 'Buyer enquiry inbox', 'Introduction calls']]];
  $('#svGrid').insertAdjacentHTML('beforebegin', '<div class="d-flex flex-wrap gap-2 mb-4" id="svChips">' + ['All', 'Verify', 'Digital', 'Advisory'].map((x, i) => `<button class="chip ${i ? '' : 'active'}" data-t="${i ? x : ''}">${x}</button>`).join('') + '</div>');
  const r = t => { $('#svGrid').innerHTML = S.map((s, i) => [s, i]).filter(x => !t || x[0][3] === t).map(([s, i]) => `<div class="col-md-6 col-lg-4"><div class="card-x sv2" data-i="${i}" tabindex="0" role="button"><span class="tag">${s[3]}</span><div class="ic"><i class="bi ${s[0]}"></i></div><h3 class="h5">${s[1]}</h3><p class="mb-0">${s[2]}</p><div class="foot2"><span>${s[4]} · from ${s[5]}</span><span class="go"><i class="bi bi-arrow-right"></i></span></div></div></div>`).join(''); };
  chips('#svChips', r); r('');
  const open = e => { const c = e.target.closest('.sv2'); if (!c || (e.type === 'keydown' && e.key !== 'Enter')) return; const s = S[+c.dataset.i]; dm(s[1], `<p>${s[6]}</p><h6>What you get</h6><ul>${s[7].map(x => `<li>${x}</li>`).join('')}</ul><p class="mb-0"><b>Time:</b> ${s[4]} · <b>From:</b> ${s[5]}</p><div class="mt-3"><a class="btn btn-green" href="contact.html">Request this service</a></div>`); };
  $('#svGrid').onclick = open; $('#svGrid').onkeydown = open; });
show('tq', () => { $('#testi .sub').insertAdjacentHTML('afterend', '<div class="tsum"><div class="card-x"><b class="big">4.9<small class="fs-6">/5</small></b><span>Average rating</span></div><div class="card-x"><b class="big"><span data-count="200">0</span>+</b><span>Client reviews</span></div><div class="card-x"><b class="big"><span data-count="92">0</span>%</b><span>Renew each year</span></div><div class="card-x">' + [['5★', 86], ['4★', 11], ['3★', 3]].map(x => `<div class="rbar"><span>${x[0]}</span><div class="bar"><i data-w="${x[1]}"></i></div><span>${x[1]}%</span></div>`).join('') + '</div></div>'); $$('.tsum [data-count],.tsum [data-w]').forEach(el => io.observe(el));
  $('#tqM').insertAdjacentHTML('afterend', '<a href="contact.html" class="btn btn-outline-success btn-sm">Share your story</a>'); });
show('mgGrid', () => { const B = ['Leads the platform. Previously ran sustainability programmes for a large textile exporter.', 'Oversees every LEED review. A LEED AP with 12 years of factory audits.', 'Builds the tour and evidence tools. Focuses on making technical data easy to read.', 'Brings factories and buyers together across 35+ countries.']; $('#mgGrid').onclick = e => { const c = e.target.closest('.card-x'); if (!c) return; const i = $$('#mgGrid .card-x').indexOf(c); dm(MG[i][0], `<p class="meta">${MG[i][1]}</p><p>${B[i]}</p>`); }; });
show('home', () => { if (!document.getElementById('wmap')) return; const L = [['home', 'Home'], ...$$('main > section[id]').map(s => [s.id, (s.querySelector('h2') || {}).textContent || s.id])]; const nv = document.createElement('nav'); nv.className = 'sdots'; nv.setAttribute('aria-label', 'Page sections'); nv.innerHTML = L.map(l => `<button data-id="${l[0]}" data-n="${l[1]}" aria-label="${l[1]}"></button>`).join(''); document.body.appendChild(nv);
  nv.onclick = e => { const b = e.target.closest('button'); if (b) document.getElementById(b.dataset.id).scrollIntoView({ behavior: 'smooth' }); };
  const o = new IntersectionObserver(es => es.forEach(x => { if (x.isIntersecting) $$('.sdots button').forEach(b => b.classList.toggle('on', b.dataset.id === x.target.id)); }), { threshold: .4 }); L.forEach(l => o.observe(document.getElementById(l[0]))); });
document.addEventListener('click', e => { const b = e.target.closest('.btn,.chip'); if (!b) return; const r = b.getBoundingClientRect(), s = document.createElement('span'); s.className = 'rip'; s.style.left = e.clientX - r.left + 'px'; s.style.top = e.clientY - r.top + 'px'; b.appendChild(s); setTimeout(() => s.remove(), 600); });
document.addEventListener('mousemove', e => { const b = e.target.closest && e.target.closest('.btn-gold,.btn-green'); if (!b || b.closest('nav')) return; const r = b.getBoundingClientRect(); b.style.transform = `translate(${Math.max(-5, Math.min(5, (e.clientX - r.left - r.width / 2) * .15))}px,${Math.max(-4, Math.min(4, (e.clientY - r.top - r.height / 2) * .2))}px)`; });
document.addEventListener('mouseout', e => { const b = e.target.closest && e.target.closest('.btn'); if (b) b.style.transform = ''; });

/* V7 */
show('tSpot', () => { const D = [['Factory', 'Our buyers now ask for the scorecard link first. Audits that took weeks take days.', 'Farhana Akter', 'Sustainability Lead, Green Textile Ltd', '1573496359142-b8d87734a5a2', ['Audit prep', '5 weeks', '2 weeks', 100, 40]], ['Factory', 'The 360° tour let a buyer inspect our dye house without flying in.', 'Minh Tran', 'Operations Director, EcoWear Co.', '1560250097-0b93528c311a', ['Buyer enquiries', '8 / month', '21 / month', 38, 100]], ['Factory', 'Benchmarking showed our water use was above peers. We fixed it in a quarter.', 'Ahmet Kaya', 'Plant Manager, HomeLoom', '1519085360753-af0119f7cbe7', ['Water use', '100%', '78%', 100, 78]], ['Buyer', 'One verified profile replaced six different supplier questionnaires.', 'Sara Lindqvist', 'Sourcing Manager, NordWear', '1580489944761-15a19d654956', ['Paperwork', '6 forms', '1 profile', 100, 17]], ['Factory', 'Gold to Platinum took two years. The scorecard showed which credits to chase.', 'Linh Pham', 'Director, ZeroLine', '1573497019940-1c28c88b4f3e', ['LEED points', '70', '84', 83, 100]], ['Buyer', 'Scorecards let us shortlist suppliers in an afternoon instead of a quarter.', 'Daniel Okoye', 'Head of Sourcing, Meridian Retail', '1507003211169-0a1dd7228f2d', ['Shortlist time', '12 weeks', '1 week', 100, 8]]];
  const likes = D.map((_, i) => [12 + i * 3, false]), ini = n => n.split(' ').map(x => x[0]).join(''), av = d => `${ini(d[2])}<img src="https://images.unsplash.com/photo-${d[4]}?auto=format&fit=crop&w=160&h=160&q=70" alt="" onerror="this.remove()">`;
  let L = D, c = 0, t, play = true; const sp = $('#tSpot');
  $('#tsum').innerHTML = '<div><b>4.9/5</b><span>Average rating</span></div><div><b>200+</b><span>Client reviews</span></div><div><b>92%</b><span>Renew each year</span></div>';
  $('#tChips').innerHTML = ['All', 'Factory', 'Buyer'].map((x, i) => `<button class="chip ${i ? '' : 'active'}" data-t="${i ? x : ''}">${x === 'All' ? 'All stories' : x + 's'}</button>`).join('');
  const wall = () => { $('#tWall').innerHTML = L.map((d, i) => `<button class="tw ${i === c ? 'on' : ''}" data-i="${i}"><span class="av3">${av(d)}</span><span class="flex-fill text-start"><b>${d[2]}</b><small>${d[3].split(', ')[1] || d[3]}</small></span><span class="tp">${d[0].toUpperCase()}</span></button>`).join(''); };
  const run = () => { clearTimeout(t); if (play) t = setTimeout(() => go(c + 1), 7000); };
  const go = i => { c = (i + L.length) % L.length; sp.classList.add('sw'); setTimeout(() => { const d = L[c], k = D.indexOf(d), m = d[5], l = likes[k];
    sp.innerHTML = `<div class="stars">★★★★★<span class="tp2">${d[0]} · Verified</span></div><blockquote>“${d[1]}”</blockquote><div class="d-flex align-items-center gap-3 mt-4"><span class="av3 big-av">${av(d)}</span><div><b>${d[2]}</b><div class="meta2">${d[3]}</div></div></div><div class="mrow"><div class="small fw-bold mb-2">${m[0]}</div><div class="mb"><span>Before</span><div class="bar"><i class="b0" data-w="${m[3]}"></i></div><span>${m[1]}</span></div><div class="mb"><span>After</span><div class="bar"><i data-w="${m[4]}"></i></div><span>${m[2]}</span></div></div><div class="d-flex gap-2 mt-3 flex-wrap"><button class="btn btn-sm btn-outline-light" data-a="like"><i class="bi bi-hand-thumbs-up${l[1] ? '-fill' : ''}"></i> Helpful (${l[0]})</button><button class="btn btn-sm btn-outline-light" data-a="copy"><i class="bi bi-clipboard"></i> Copy quote</button><span class="ms-auto d-flex gap-2"><button class="btn btn-sm btn-outline-light" data-a="prev" aria-label="Previous"><i class="bi bi-arrow-left"></i></button><button class="btn btn-sm btn-outline-light" data-a="play" aria-label="Pause or play"><i class="bi bi-${play ? 'pause' : 'play'}-fill"></i></button><button class="btn btn-sm btn-outline-light" data-a="next" aria-label="Next"><i class="bi bi-arrow-right"></i></button></span></div><div class="tqbar"><i></i></div>`;
    sp.classList.remove('sw'); sp.classList.toggle('paused', !play); setTimeout(() => $$('#tSpot [data-w]').forEach(e => e.style.width = e.dataset.w + '%'), 60); }, 220); wall(); run(); };
  sp.onclick = e => { const b = e.target.closest('[data-a]'); if (!b) return; const a = b.dataset.a, k = D.indexOf(L[c]);
    if (a === 'prev') go(c - 1); else if (a === 'next') go(c + 1);
    else if (a === 'play') { play = !play; b.innerHTML = `<i class="bi bi-${play ? 'pause' : 'play'}-fill"></i>`; sp.classList.toggle('paused', !play); run(); }
    else if (a === 'like') { likes[k][1] = !likes[k][1]; likes[k][0] += likes[k][1] ? 1 : -1; b.innerHTML = `<i class="bi bi-hand-thumbs-up${likes[k][1] ? '-fill' : ''}"></i> Helpful (${likes[k][0]})`; }
    else { try { navigator.clipboard.writeText(L[c][1]); } catch (x) {} toast('Quote copied.'); } };
  $('#tWall').onclick = e => { const b = e.target.closest('.tw'); if (b) go(+b.dataset.i); };
  sp.onmouseenter = () => clearTimeout(t); sp.onmouseleave = run;
  sp.onkeydown = e => { if (e.key === 'ArrowRight') go(c + 1); if (e.key === 'ArrowLeft') go(c - 1); };
  let sx = null; sp.addEventListener('pointerdown', e => { sx = e.clientX; }); sp.addEventListener('pointerup', e => { if (sx !== null && Math.abs(e.clientX - sx) > 70 && !e.target.closest('button')) go(c + (e.clientX < sx ? 1 : -1)); sx = null; });
  chips('#tChips', f => { L = f ? D.filter(d => d[0] === f) : D; go(0); }); go(0); });
show('news', () => { $$('.fcol h6').forEach(h => { const f = () => { if (innerWidth < 768) h.parentElement.classList.toggle('open'); }; h.onclick = f; h.onkeydown = e => { if (e.key === 'Enter') f(); }; });
  $('#ftTop').onclick = () => scrollTo({ top: 0, behavior: 'smooth' });
  const n = $('#news'); n.addEventListener('submit', () => { if (n.checkValidity()) { const b = n.querySelector('.btn'); b.classList.add('ok'); b.innerHTML = 'Subscribed <i class="bi bi-check2"></i>'; setTimeout(() => { b.classList.remove('ok'); b.textContent = 'Subscribe'; }, 3000); } }); });
$$('.dark').forEach(s => s.addEventListener('mousemove', e => { const r = s.getBoundingClientRect(); s.style.setProperty('--mx', e.clientX - r.left + 'px'); s.style.setProperty('--my', e.clientY - r.top + 'px'); }));
show('fotm', () => { const lab = $$('#fotm .small.mb-1'), bars = $$('#fotm .bar i'); if (!lab[0]) return; const Y = { 25: [['Renewable energy', 64], ['Water reuse', 58], ['Waste recycling', 88], 'Gold'], 26: [['Renewable energy', 81], ['Water reuse', 74], ['Waste recycling', 95], 'Platinum'] };
  lab[0].insertAdjacentHTML('beforebegin', '<div class="seg mb-3" id="foSeg"><button data-y="25">2025 · Gold</button><button class="on" data-y="26">2026 · Platinum</button></div>');
  $('#foSeg').onclick = e => { const b = e.target.closest('button'); if (!b) return; $$('#foSeg button').forEach(x => x.classList.toggle('on', x === b)); const y = Y[b.dataset.y]; lab.forEach((l, i) => { l.textContent = `${y[i][0]} ${y[i][1]}%`; bars[i].style.width = y[i][1] + '%'; }); const lv2 = $('#fotm .lvl'); lv2.className = 'lvl lvl-' + y[3]; lv2.textContent = 'LEED ' + y[3]; }; });

/* V8 */
(() => { const dd = document.querySelector('.navbar .dropdown'); if (!dd) return; const mq = matchMedia('(min-width:1200px) and (hover:hover)'), mn = dd.querySelector('.dropdown-menu'), tg = dd.querySelector('.dropdown-toggle'); let t;
  const set = o => { dd.classList.toggle('show', o); mn.classList.toggle('show', o); tg.classList.toggle('show', o); tg.setAttribute('aria-expanded', o); };
  dd.addEventListener('mouseenter', () => { if (mq.matches) { clearTimeout(t); set(true); } }); dd.addEventListener('mouseleave', () => { if (mq.matches) t = setTimeout(() => set(false), 180); });
  tg.addEventListener('click', e => { if (mq.matches) { e.preventDefault(); e.stopImmediatePropagation(); set(!mn.classList.contains('show')); } }, true); })();
show('lmap', () => { const box = $('#lmap'); if (!window.L) { box.innerHTML = '<p class="p-4">The map needs an internet connection to load.</p>'; return; }
  const G = { Dhaka: [23.81, 90.41], Hanoi: [21.03, 105.85], Pune: [18.52, 73.86], Istanbul: [41.01, 28.98], Chennai: [13.08, 80.27], Gazipur: [24.0, 90.42], 'Ho Chi Minh City': [10.82, 106.63], Bursa: [40.19, 29.06], Bengaluru: [12.97, 77.59], Narayanganj: [23.62, 90.5], Danang: [16.05, 108.2], Izmir: [38.42, 27.14] };
  const map = L.map('lmap', { scrollWheelZoom: false, worldCopyJump: true }).setView([22, 70], 3);
  const Bs = { Light: L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png', { maxZoom: 19, attribution: '© OpenStreetMap © CARTO' }), Standard: L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, attribution: '© OpenStreetMap contributors' }), Satellite: L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', { maxZoom: 18, attribution: 'Tiles © Esri' }) };
  Bs.Light.addTo(map); L.control.layers(Bs, null, { position: 'topright' }).addTo(map); L.control.scale({ position: 'bottomleft' }).addTo(map);
  map.on('click', () => map.scrollWheelZoom.enable()); box.addEventListener('mouseleave', () => map.scrollWheelZoom.disable());
  const Btn = (html, title, fn) => { const C = L.Control.extend({ options: { position: 'topleft' }, onAdd() { const b = L.DomUtil.create('button', 'lbtn'); b.innerHTML = html; b.title = title; b.type = 'button'; b.setAttribute('aria-label', title); L.DomEvent.disableClickPropagation(b); b.onclick = () => fn(b); return b; } }); return new C().addTo(map); };
  const pins = F.map((f, i) => L.marker(G[f[2]], { icon: L.divIcon({ className: '', html: `<span class="pin pin-${f[5]}"><i class="bi bi-buildings-fill"></i></span>`, iconSize: [34, 34], iconAnchor: [17, 17], popupAnchor: [0, -18] }) }).bindTooltip(f[0], { direction: 'top', offset: [0, -16] }).bindPopup(`<b>${f[0]}</b><br>${f[2]}, ${f[3]}<br>${lv(f[5])}${f[7] ? ' · 360° tour' : ''}<div class="small mt-2">Sustainability ${f[6]}%</div><div class="pbar"><i style="width:${f[6]}%"></i></div><a class="d-block mt-2" href="factory-details.html?id=${i}">View details →</a>`));
  const grp = L.markerClusterGroup ? L.markerClusterGroup({ showCoverageOnHover: false, maxClusterRadius: 45 }) : L.layerGroup(); map.addLayer(grp);
  let lvl = '', q = '', vis = [], ring, you; const mark = i => { if (ring) map.removeLayer(ring); ring = L.circle(G[F[i][2]], { radius: 60000, color: '#C9A227', weight: 2, fillOpacity: .12 }).addTo(map); };
  const draw = fit => { grp.clearLayers(); vis = F.map((f, i) => i).filter(i => (!lvl || (lvl === '360' ? F[i][7] : F[i][5] === lvl)) && (!q || (F[i][0] + F[i][2] + F[i][3]).toLowerCase().includes(q))); vis.forEach(i => grp.addLayer(pins[i]));
    $('#mList').innerHTML = vis.map(i => `<button class="ml" data-i="${i}"><span class="pinm pin-${F[i][5]}"></span><span><b>${F[i][0]}</b><small>${F[i][2]}, ${F[i][3]}</small></span><span>${F[i][6]}%</span></button>`).join('') || '<p>No factories match.</p>'; $('#mCount').textContent = vis.length + ' of ' + F.length + ' factories shown';
    if (fit && vis.length) map.flyToBounds(L.latLngBounds(vis.map(i => G[F[i][2]])).pad(.3), { duration: 1 }); };
  const fly = i => { mark(i); map.flyTo(G[F[i][2]], 7, { duration: 1.1 }); map.once('moveend', () => grp.zoomToShowLayer ? grp.zoomToShowLayer(pins[i], () => pins[i].openPopup()) : pins[i].openPopup()); };
  $('#mList').onclick = e => { const b = e.target.closest('.ml'); if (b) fly(+b.dataset.i); };
  $('#mList').onmouseover = e => { const b = e.target.closest('.ml'); $$('.leaflet-marker-icon.hl').forEach(x => x.classList.remove('hl')); if (b) pins[+b.dataset.i].getElement()?.classList.add('hl'); };
  $('#mChips').innerHTML = [['All', ''], ['Platinum', 'Platinum'], ['Gold', 'Gold'], ['Silver', 'Silver'], ['Certified', 'Certified'], ['360° tours', '360']].map((x, i) => `<button class="chip ${i ? '' : 'active'}" data-t="${x[1]}">${x[0]}</button>`).join(''); chips('#mChips', t => { lvl = t; draw(true); });
  $('#mQ').oninput = e => { q = e.target.value.toLowerCase(); draw(true); };
  $('#mCount').insertAdjacentHTML('afterend', '<div id="mCoord" class="small text-muted"></div>'); map.on('mousemove', e => $('#mCoord').textContent = `Cursor: ${e.latlng.lat.toFixed(2)}, ${e.latlng.lng.toFixed(2)}`);
  Btn('<i class="bi bi-house"></i>', 'Reset view', () => { map.closePopup(); if (ring) map.removeLayer(ring); if (you) map.removeLayer(you); draw(true); });
  Btn('<i class="bi bi-crosshair"></i>', 'Find the nearest factory', () => { if (!navigator.geolocation) { toast('Location is not available in this browser.'); return; } navigator.geolocation.getCurrentPosition(p => { const me = [p.coords.latitude, p.coords.longitude]; let bi = 0, bd = 1e12; F.forEach((f, i) => { const d = map.distance(me, G[f[2]]); if (d < bd) { bd = d; bi = i; } }); if (you) map.removeLayer(you); you = L.layerGroup([L.circleMarker(me, { radius: 8, color: '#fff', fillColor: '#2a6f8a', fillOpacity: 1, weight: 3 }), L.polyline([me, G[F[bi][2]]], { color: '#C9A227', dashArray: '6 8' })]).addTo(map); map.fitBounds(L.latLngBounds([me, G[F[bi][2]]]).pad(.3)); toast(`Nearest: ${F[bi][0]} (${Math.round(bd / 1000).toLocaleString()} km away)`); }, () => toast('Location permission was not granted.')); });
  let tour = 0, k = 0; Btn('<i class="bi bi-play-fill"></i>', 'Auto-tour', b => { if (tour) { clearInterval(tour); tour = 0; b.innerHTML = '<i class="bi bi-play-fill"></i>'; } else { b.innerHTML = '<i class="bi bi-pause-fill"></i>'; const go = () => { if (vis.length) fly(vis[k++ % vis.length]); }; go(); tour = setInterval(go, 5000); } });
  Btn('<i class="bi bi-arrows-fullscreen"></i>', 'Fullscreen', () => document.fullscreenElement ? document.exitFullscreen() : $('#mapWrap').requestFullscreen?.()); document.addEventListener('fullscreenchange', () => setTimeout(() => map.invalidateSize(), 200));
  draw(false); setTimeout(() => map.invalidateSize(), 300); });
show('mgGrid', () => { const T = [['Rahim Chowdhury', 'Chief Executive', 'Leadership', 18, 'Sets the platform strategy. Previously ran sustainability programmes for a large textile exporter.', ['Strategy', 'Supply chains', 'Policy'], '1500648767791-00dcc994a43e'], ['Nadia Rahman', 'Chief Operating Officer', 'Leadership', 14, 'Runs day-to-day delivery across verification, tours and client support.', ['Operations', 'Finance', 'Hiring'], '1438761681033-6461ffad8d80'], ['Linh Tran', 'Head of LEED Verification', 'LEED Review', 12, 'A LEED AP who leads every credit review and signs off published scorecards.', ['LEED v4', 'Energy modelling', 'Audits'], '1544005313-94ddf0286df2'], ['Omar Haddad', 'Senior LEED Reviewer', 'LEED Review', 9, 'Reviews water and materials credits for textile and electronics sites.', ['Water', 'Materials', 'Evidence checks'], '1506794778202-cad84cf45f1d'], ['Aylin Demir', 'Director of Technology', 'Technology', 11, 'Builds the tour and evidence tools, and keeps the data easy to read.', ['Web platforms', '360° capture', 'Data viz'], '1487412720507-e7ab37603c6f'], ['Kenji Mori', 'Lead Engineer', 'Technology', 8, 'Maintains the scorecard engine and benchmarking pipeline.', ['JavaScript', 'APIs', 'Charts'], '1492562080023-ab3db95bfbce'], ['Priya Nair', 'Head of Partnerships', 'Partnerships', 10, 'Brings factories and buyers together across 35+ countries.', ['Negotiation', 'Buyer programmes', 'Events'], '1534528741775-53994a69daeb'], ['Elena Rossi', 'Buyer Relations Manager', 'Partnerships', 7, 'Helps buyers shortlist suppliers and read scorecards with confidence.', ['Sourcing', 'Training', 'Reporting'], '1494790108377-be9c29b29330']];
  const ini = n => n.split(' ').map(x => x[0]).join(''), ph = d => `${ini(d[0])}<img src="https://images.unsplash.com/photo-${d[6]}?auto=format&fit=crop&w=240&h=240&q=70" alt="" onerror="this.remove()">`;
  $('#mgGrid').insertAdjacentHTML('beforebegin', '<div class="d-flex flex-wrap gap-2 mb-4" id="tmChips">' + ['All', 'Leadership', 'LEED Review', 'Technology', 'Partnerships'].map((x, i) => `<button class="chip ${i ? '' : 'active'}" data-t="${i ? x : ''}">${x}</button>`).join('') + '</div>'); $$('#mgmt [data-count]').forEach(el => io.observe(el));
  const r = t => { $('#mgGrid').innerHTML = T.map((d, i) => [d, i]).filter(x => !t || x[0][2] === t).map(([d, i]) => `<div class="col-6 col-lg-3"><div class="card-x tm" data-i="${i}" tabindex="0" role="button"><div class="ph0">${ph(d)}</div><h3 class="h6 mb-0">${d[0]}</h3><p class="meta mb-0">${d[1]}</p><div class="tags"><span>${d[2]}</span><span>${d[3]} yrs</span></div></div></div>`).join('') + (t ? '' : '<div class="col-6 col-lg-3"><a class="card-x join text-center text-decoration-none" href="contact.html"><i class="bi bi-plus-circle fs-1"></i><b>We are hiring</b><small>See open roles</small></a></div>'); };
  chips('#tmChips', r); r('');
  const open = e => { const c = e.target.closest('.tm'); if (!c || (e.type === 'keydown' && e.key !== 'Enter')) return; const d = T[+c.dataset.i]; dm(d[0], `<div class="d-flex gap-3 align-items-center mb-3"><span class="ph0" style="width:84px;height:84px;margin:0;font-size:1.4rem;position:relative;overflow:hidden;border-radius:50%;display:grid;place-items:center;background:var(--g2);color:#fff">${ph(d)}</span><div><b>${d[1]}</b><div class="meta">${d[2]} · ${d[3]} years in the field</div></div></div><p>${d[4]}</p><h6>Expertise</h6>${d[5].map((s, j) => `<div class="mb-2"><div class="small fw-bold">${s}</div><div class="bar"><i style="width:${90 - j * 10}%"></i></div></div>`).join('')}<a class="btn btn-green mt-3" href="contact.html">Contact ${d[0].split(' ')[0]}</a>`); };
  $('#mgGrid').onclick = open; $('#mgGrid').onkeydown = open; });
document.addEventListener('click', e => { const im = e.target.closest('.fcard .ph'); if (!im) return; e.stopImmediatePropagation(); const c = im.closest('.fcard'), a = c.querySelector('a[href]'); dm(c.querySelector('h3').textContent, `<div class="d-flex flex-wrap gap-2 mb-2">${c.querySelector('.d-flex').innerHTML}</div><p class="meta">${[...c.querySelectorAll('.meta')].map(x => x.textContent).join('<br>')}</p><a class="btn btn-green" href="${a.href}">Open full details</a>`); }, true);
document.addEventListener('click', e => { const tr = e.target.closest('#fiBody tr'); if (!tr) return; const i = F.findIndex(f => f[0] === tr.querySelector('b').textContent); if (i > -1) location.href = 'factory-details.html?id=' + i; });
document.addEventListener('click', e => { const l = e.target.closest('#clTrack .logo'); if (l) dm(l.textContent, `<p>${l.textContent} is a verified client. Its scorecard, KPIs and 360° tour are public in the directory.</p><a class="btn btn-green" href="factories.html">Browse the directory</a>`); });

show('nlGrid', () => { let t = '', q = ''; $('#nlChips').innerHTML = ['All', 'Platform', 'LEED', 'Industry', 'Case Study'].map((x, i) => `<button class="chip ${i ? '' : 'active'}" data-t="${i ? x : ''}">${x}</button>`).join('');
  const r = () => { const L = NEWS.map((n, i) => [n, i]).filter(x => (!t || x[0][0] === t) && (!q || (x[0][2] + x[0][3]).toLowerCase().includes(q))); $('#nlGrid').innerHTML = L.map(([n, i]) => `<div class="col-md-6 col-lg-4"><article class="acard"><a href="news-details.html?id=${i}" class="text-decoration-none text-reset"><div class="ph ${nth(i)}"></div><div class="body"><small>${n[0]} · ${n[1]} · ${n[4]} min</small><h3 class="h6 mt-1">${n[2]}</h3><p class="small">${n[3]}</p><span class="fw-bold text-success">Read story →</span></div></a></article></div>`).join('') || '<p>No stories match.</p>'; };
  chips('#nlChips', x => { t = x; r(); }); $('#nlQ').oninput = e => { q = e.target.value.toLowerCase(); r(); }; r(); });
})();
